name: sr_barbara_fl
dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.0
  sqflite: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.0